### ISSUE TITLE
Accessibility Work on Mobile Layout

### ISSUE THREAD

**Issue by technbuzz** [pkgeography/geography.pk#1]
## Tab Index for for Hamburger Icon

We have no tab index for hamburger icon for users that don't have the mouse and surf with keyboard only
## No Responsive Menu

We have no responsive menu when JavaScript Disabled the, hamburger won't work in that case

**Comment by jabranr** [comment]
:+1:

**Comment by technbuzz** [comment]
I should have pulled the request but I don't know the rules for that, and what code standard you gonna implement.

**Comment by jabranr** [comment]
@samiullah1989 You should do that if it is possible. Rules/standards are that code should be commented and indented properly so it is understandable now and later.
